apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: grafana
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000  # You can specify a port or let Kubernetes assign one
  selector:
    app.kubernetes.io/name: grafana
